### ISSUE TITLE
Refactor Code

### ISSUE THREAD

**Issue by lucasqueiroz** [lucasqueiroz/br-generator#1]
# Refactor Code

# Description
The code needs a big refactor, to make it easier to read, and to run faster.
I've already started a refactor, but I'll not be able to do everything by myself, and the way I did it, the whole project would have to be re-created. Maybe it would be better to start a new refactor, and do it in multiple branches, then merge them all to a big refactor branch.

**Comment by divyanshumehta** [comment]
@lucasqueiroz do u intend to use RuboCop for maintaining a fixed style throughout the project. I so we can decide here what all cops to include

**Comment by lucasqueiroz** [comment]
@divyanshumehta Yes, that is the plan. I don't really know what cops to use, but in the refactor, I was using the default code style for RuboCop.

**Comment by divyanshumehta** [comment]
I will slowly add other cops and their corrections. I think a better approach would be to add and implement each cop in a different issue. It would make the process more modular. I have seen big projects refactor for each cop in a diferent issue.

**Comment by lucasqueiroz** [comment]
@divyanshumehta sounds great, thanks a lot!
I will keep refactoring the project as well, and adding more items to it.

**Comment by jaysonesmith** [comment]
See my PR for more info, but I've got you guys started on the rubocop journey with `rubocop --auto-gen-config`  :)
