### ISSUE TITLE
Add more banks

### ISSUE THREAD

**Issue by lucasqueiroz** [lucasqueiroz/br-generator#3]
This issue is related to adding more banks.
Possible banks that can be added in the future:

- Caixa Economica Federal
- Banrisul
- Sicoob

More to come.

**Comment by Atul9** [comment]
@lucasqueiroz what are the bank codes ?

**Comment by lucasqueiroz** [comment]
@Atul9 
`Banrisul - 041`
`Caixa Economica Federal - 104`
`Sicoob - 756 (Officially named Bancoob)`
The real problem isn't the bank code, but their verification digits. For Caixa, for example, the documentation is really hard to find, and some other banks don't even have that documented...

**Comment by Atul9** [comment]
@lucasqueiroz I am new to this. Can you please suggest how to go about this?

**Comment by lucasqueiroz** [comment]
@Atul9 Sadly, there is no guide... Basically, we need to search on Google for the documentation for each bank and hope that it is updated and has the verification digit calculation instructions. All the documents are in Portuguese though, so I think this makes it even more difficult...
